# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.8"
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install .
# different stages in the pipeline
stages:
  - Static Analysis
  - Test
#defines the job in Static Analysis
black:
  stage: Static Analysis
  script:
  - black .

unit-test-job:
  stage: Test
  script:
    - python ./tests/unit_test_metrics.py
    - python ./tests/unit_test_dim_reduction.py
    - python ./tests/unit_test_uncertainty_estimation.py
    - python ./tests/unit_test_detection_dataset.py

integration-tests-job:
  stage: Test
  script:
    - python ./tests/integration_tests.py