# Uncomment only for IRT git repo
#include:
#  - project: 'confianceai/ec_1/fa2_infrastructure/gitlab-ci-pipelines'
#    ref: master
#    file: 'python-lib-build.gitlab-ci.yml'

image: "python:3.8"
#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install .
# different stages in the pipeline
stages:
  - Static Analysis
  - Test
#defines the job in Static Analysis
black:
  stage: Static Analysis
  script:
  - black .

unit-test-job:
  stage: Test
  script:
    - python ./tests/unit_test_metrics.py
    - python ./tests/unit_test_dim_reduction.py
    - python ./tests/unit_test_uncertainty_estimation.py
    - python ./tests/unit_test_detection_dataset.py

integration-tests-job:
  stage: Test
  script:
    - python ./tests/integration_tests.py